### GET request to example server
GET https://examples.http-client.intellij.net/get?generated-in=IntelliJ IDEA

###
POST https://examples.http-client.intellij.net/post
Accept: application/json
Content-Type: application/json

{
  "message": "Hello World"
}


###
POST https://api.paat.party/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "billy@email.com",
  "password": "abc"
}


### login api
POST https://api.paat.party/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "billy@email.com",
  "password": "abc"
}
